### ISSUE TITLE
Any new release plan, which include several important bug fixes? :)

### ISSUE THREAD

**Issue by Senorsen** [sighupio/permission-manager#107]
Hi, this is a very wonderful project, it helps us manage small clusters easily.

The current latest release (v1.7.1-rc1) includes several bugs, which have been fixed by #88, #90, etc.

We'd appreciate it if you can release a new version.

**Comment by mgeri** [comment]
I agree with @Senorsen. This project helps a lot of small and dedicated cluster management.
It would be great to have a new release with the already fixed bugs.

**Comment by runzhliu** [comment]
https://hub.docker.com/repository/docker/runzhliu/permission-manager

**Comment by luigibarbato** [comment]
Hi guys! Thank you so much for your interest and especially for waiting 😊. We are in the process of bringing back an active development of the Permission Manager, stay tuned 💪🏾

**Comment by luigibarbato** [comment]
UPDATE: We've just released `v1.8.0`.

https://github.com/sighupio/permission-manager/discussions/146

🤟🏽🎸
