### ISSUE TITLE
will crash if trying to add an user which already exists

### ISSUE THREAD

**Issue by viorel-anghel** [sighupio/permission-manager#11]
when trying (by mistake) to add an user with a name which already exists as rolebinding, it will crash with no explanation. i have had previously created a ServiceAccount/Role/RoleBinding using standard  k8 yaml.

**Comment by ralgozino** [comment]
Hi @viorel-anghel ! Thanks for reaching out.

I'm not able to reproduce the issue. This are the steps I followed:

1. Created a rolebinding with name `myuser` in the namespace permission-manager (the namespace where is deployed the app) with this command:

```shell
$ kubectl create rolebinding -n permission-manager myuser --role admin --serviceaccount permission-manager:myuser
```

2. Went to permission-manager UI and created a `myuser` user and it got created without crashing.

Could you please give as a step by step on how to reproduce this?

Thanks!

**Comment by angelbarrera92** [comment]
After a month without any response, I proceed to close the issue. Don't doubt to re-open it if you face the error again.

Thanks!
