### ISSUE TITLE
Permissions change when namespace is deleted

### ISSUE THREAD

**Issue by robert83ft** [sighupio/permission-manager#111]
I think permission manager should somehow store a desired configuration and try to get back to it as much as possible.
I found that if a namespace is deleted and that namespace was configured on a user it is than removed. Which is normal.
However I recreated the namespace and obviously (maybe it's impossible or there is a technical limitation) was not re-added.

So, all in all, if you set
User1 - namespace A and namespace B
You delete and recreate namespace A
My expectation is that A is again allowed for User1.

However I might be wrong here.

**Comment by luigibarbato** [comment]
This is not the behavior we expect, so I close the issue
