### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ladung** [sighupio/permission-manager#115]
when I created user, i used kubeconfig which generated by webUI and I had problem:
```
╰─ k get node -o wide
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Comment by ladung** [comment]
Why do not show `certificate-authority-data` ???
![image](https://user-images.githubusercontent.com/43999277/189793152-f9770814-610a-4e00-9278-461612088000.png)

**Comment by colegatron** [comment]
Using latest version:
kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.1-rc1/crd.yml
kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.1-rc1/seed.yml
kubectl apply -f https://github.com/sighupio/permission-manager/releases/download/v1.7.1-rc1/deploy.yml

Not working for me either. Certificate-authority-data is not dumped into the kubeconfig.
You can workaround it copying it from your existing admin kubeconfig

**Comment by windghoul** [comment]
some thing wrong in internal/resources/serviceaccount.go:57, secret name should be serviceAccount.Secrets[0].Name not username

**Comment by ladung** [comment]
@windghoul thank you so much! let's me try reinstall!

**Comment by ladung** [comment]
@windghoul your commit is not merge?

**Comment by windghoul** [comment]
> 
@ladung 
yeah, you can build locally with reference to my modification, the build command is
```
docker build -t permission-manager:<you version> .
```
i'm already test in my cluster.

**Comment by luigibarbato** [comment]
Hello, Luigi is here 🖖🏾 

Forgive me but I can't reproduce your problem, could I have some more information?

1. The permission manager in what namespace are you deploying it?
2. What version of kube are you using? 
3. Are you using the helm chart?

Thank you for your collaboration :)

**Comment by windghoul** [comment]
> 
@luigibarbato hi,
1. In which namespace are you deploying the permission manager? namespace is permission-manager
<img width="552" alt="image" src="https://user-images.githubusercontent.com/16053291/216877131-ba0726d0-f7fd-4f8d-8065-248f07d01d95.png">
2. What version of kube are you using?
v1.20.6
I didn't test on a lower version cluster, so I don't know if the problem is caused by the version of the cluster
4. Are you using the helm chart?
no, I don't use helm chart.
I use the kubectl apply -f to install permission manager.

**Comment by luigibarbato** [comment]
Hi guys! As I commented in #141, you can safely update the Permission Manager to the latest version where this bug is fixed and generally, there are a lot of improvements.

Thank you for your contribution :)
