### ISSUE TITLE
Installation Document Error

### ISSUE THREAD

**Issue by bobmerevel** [sighupio/permission-manager#154]
Hi,
Thank you for all development. It is really usefull app for me :) 

I want to report so small issue on installation document. Last part of installation document at deployment yaml file container tag is 1.8 at https://github.com/sighupio/permission-manager/releases/download/v1.8.0/deploy.yml, but image is builded as v1.8.

Best regards,

**Comment by luigibarbato** [comment]
@bobmerevel Hey! 👋🏾  Thank you so much for the issue! and nice catch 👏🏾

**Comment by luigibarbato** [comment]
I updated the `deploy.yml` file with the container tag's fix. Thanks again :)

**Comment by bobmerevel** [comment]
Thank you for your support :)
