### ISSUE TITLE
Find a better helm-chart tag's way

### ISSUE THREAD

**Issue by luigibarbato** [sighupio/permission-manager#158]
Actually, the versioning history of our helm-chart releases is broken.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/50343470/227001809-d070db22-7f6e-4750-8940-81af1b3295fa.png">

We have to find a better helm-chart tag's handling way

**Comment by luigibarbato** [comment]
NOTE: Check if is possible to filter changelog history by path.

**Comment by loeken** [comment]
it seems that the docs use a tag of 1.8.0/1.9.0 but the actual image is tagged with v1.8.0 and v1.9.0 kinda confusing ;)
