### ISSUE TITLE
Update UI's stack

### ISSUE THREAD

**Issue by luigibarbato** [sighupio/permission-manager#161]
Please rewrite the UI of permission manager from scratch.

It will need to have the same functionality of the current one, and it will serve as a basis for future iterations.

Please consider using with the following blocks:
- React Query
- ElasticUI
- CRA

Also take some time to setup some Code Quality tools such as ESLint, Prettier and Husky.

PR / branch: https://github.com/sighupio/permission-manager/pull/166

**Comment by nutellinoit** [comment]
Closing as stale
