### ISSUE TITLE
Evolve frontend deployment

### ISSUE THREAD

**Issue by omissis** [sighupio/permission-manager#162]
- [X] fix current issue on intel machine (dev env not starting)
- [X] remove frontend embedding from go server
- [X] move the frontend to a dedicated deployment in the helm chart
- [X] setup a local development solution that supports hot reload
- [ ] setup an nginx to serve static files on production

**Comment by AndreaDellaValle** [comment]
Branch / PR: https://github.com/sighupio/permission-manager/pull/165

**Comment by nutellinoit** [comment]
Closing as stale
