### ISSUE TITLE
How do with EKS ? 

### ISSUE THREAD

**Issue by sureshamk** [sighupio/permission-manager#18]
I tried with AKS, it works well. When I try with EKS, this approach failed due to IAM based authentication. Any workaround?

**Comment by phisco** [comment]
Authentication with EKS is a bit tricky, we are currently working on it.
@iknite feel free to add any detail.

**Comment by iknite** [comment]
Yes, We're currently working on providing ServiceAccounts because X509 keys didn't work. there is some history in #8. I will update both issues as soon as we have a PR

**Comment by angelbarrera92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change permission-manager from X509 to serviceAccount (to be used in EKS clusters)](https://trello.com/c/xkbQNEKJ/174-change-permission-manager-from-x509-to-serviceaccount-to-be-used-in-eks-clusters)

**Comment by omerfsen** [comment]
Watching this +1

**Comment by edubacco** [comment]
+1 from here too =)

**Comment by anarcher** [comment]
+1 me too :-)
