### ISSUE TITLE
Please enter Username:

### ISSUE THREAD

**Issue by cherkavi** [sighupio/permission-manager#20]
User "student1" created without errors.

ClusterRole-----<>ClusterRoleBinding
both are exist
```bash
ubectl describe clusterRoleBinding/student1___template-cluster-resources___read-only
Name:         student1___template-cluster-resources___read-only
Labels:       generated_for_user=
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  template-cluster-resources___read-only
Subjects:
  Kind  Name      Namespace
  ----  ----      ---------
  User  student1  
```

Any commands are return next error message:
```bash
kubectl --kubeconfig=/home/user/.kube/config-student1 get nodes
```
output
```bash
Please enter Username:
```

**Comment by iknite** [comment]
Hi @cherkavi can you share some environment information? (kubernetes version, pod logs...)

**Comment by cherkavi** [comment]
didn't read documentation properly

**Comment by hreidar** [comment]
Hi, @cherkavi, can you please inform us what you saw in the docs? I'm experiencing the same thing. I'm asked for user and pass which I don't remember I choose in the user creation process.

**Comment by iknite** [comment]
You can retrieve it with `kubectl  get secret permission-manager -n permission-manager -o yaml` look for "BASIC_AUTH_PASSWORD":"---your-password---"

**Comment by hreidar** [comment]
Hi, do you mean that my users do have to use the admin user and pass to be able to communicate with the server?

**Comment by hreidar** [comment]
I did try that with out any luck. 

```
kubectl get nodes
Please enter Username: admin
Please enter Password: 
error: the server doesn't have a resource type "nodes"
```

**Comment by iknite** [comment]
Sorry, I was assuming it was an issue entering in the permission-manager UI.

Could you get us more information? (platform, installation process, etc..)?

**Comment by hreidar** [comment]
Hi, no no, that is working. I did create one user (myself), got the kube/config data and put it in my kube/config. Using that context I get promoted with user and pass.

I'm testing this on a local cluster made with kubeadm, it is k8s v1.18.2. It is running on Ubuntu 18.04 nodes. What information do you need?

**Comment by iknite** [comment]
I've just created a cluster in 1.18.2 and it's working:
```
make seed
k apply -f deployments/kubernetes/deploy.yml
make port-forward &
# create a user in the UI (developer, namespace: permission-manager, cluster: none)
# export credentials to ./kube.config
k --kubeconfig=./kube.config get pods -A # should fail
k --kubeconfig=./kube.config get pods -n permission-manager # should work
```

**Comment by hreidar** [comment]
Ok, so I'm doing something wrong I guess. Do you get promoted for user and pass as you commit your commands? Is that normal?

**Comment by iknite** [comment]
No, that's something I cannot reproduce, sorry.

**Comment by iknite** [comment]
@cherkavi Could you helps us indentify what's going on? 🙏

**Comment by hreidar** [comment]
@iknite , @cherkavi, I'm available if you need me to test somethings

**Comment by hreidar** [comment]
Hi, any new on this?

**Comment by iknite** [comment]
We're storing every information here, so no, we have no further information

**Comment by angelbarrera92** [comment]
The original issue was open by @cherkavi, if the issue persists, please open a new one
