### ISSUE TITLE
Stuck on ...loding after changing CONTROL_PLANE_ADDRESS after initial deployment

### ISSUE THREAD

**Issue by hreidar** [sighupio/permission-manager#22]
Hi, I managed to deploy your app and created several users. I then noticed that the server address in the kube config file pointed to the internal address of the api-server as I configured that in the beginning. I then changed the address to my external api-server loadbalancer address and now the app is stuck on ...loading when trying to list the available users. I try to change the address back to the internal address but I can't get the app to load the user list. It hangs for a while and then dies.

Any ideas? There is nothing in the log. I've tried to restart the pod several times now.

**Comment by atosatto** [comment]
I suspect the fact that in #27 we use `controller-runtime` to connect to the K8s cluster might help with this.

**Comment by hreidar** [comment]
This is working for me in version v1.6.0, thanks.
