### ISSUE TITLE
Proposal: tag releases on the git repository

### ISSUE THREAD

**Issue by atosatto** [sighupio/permission-manager#26]
Looking at https://quay.io/repository/sighup/permission-manager?tab=tags I've found that two tags of the permission-manager image exists at the moment: 1.5.0 and 1.6.0-dev.
However, looking at the git repository it is not clear to which git commit hashes these versions corresponds.

I must admit that I haven't looked too much in depth into the content of the images to see whether there is any metadata allowing to related these to the git commits hash, but it would be cool having tags of the Docker image corresponding to tags in the git repository in order to ease the version of the application and issues troubleshooting.

**Comment by iknite** [comment]
We're un a huge refactor and its already on it. Thanks for the tip! It is good to know is something useful.
