### ISSUE TITLE
Set namespace in generated kubeconfig

### ISSUE THREAD

**Issue by 15below-adamhancock** [sighupio/permission-manager#29]
The generated kubeconfig doesn't have a namespace set in the context. 

If the user doesn't have access the default namespace then they get access denied unless they specify namespace. 

Can we have an option to set the namespace in the generated kubeconfig?

**Comment by phisco** [comment]
what would be a safe default in your opinion?
maybe one of the namespaces the user has been granted access to? what if the user is given a cluster role?
