### ISSUE TITLE
Integrations with LDAP/OpenID

### ISSUE THREAD

**Issue by dyennam** [sighupio/permission-manager#3]
Hello,
Is there possibility to have any integrations with LDAP with the tool. 
That would be a killer feature for us.

**Comment by angelbarrera92** [comment]
Hi @dyennam!

I don't know if you are looking for a way to authenticate through LDAP or to manage authorization.
Currently this project only takes care about authorization (binding users to roles).

**Comment by dyennam** [comment]
Hi @angelbarrera92 
I was more looking for something along the lines of how Jenkins uses LDAP to add users. But then we manage their authorizations via jenkins itself. 
We are trying to avoid adding users manually.

**Comment by angelbarrera92** [comment]
> Hi @angelbarrera92
> I was more looking for something along the lines of how Jenkins uses LDAP to add users. But then we manage their authorizations via jenkins itself.
> We are trying to avoid adding users manually.

Hi, sorry for the late response. 

We are not sure about what Jenkins does. Can you provide some kind of flow description about how Jenkins does it?
