### ISSUE TITLE
how to upgrade from 1.5 to 1.6?

### ISSUE THREAD

**Issue by viorel-anghel** [sighupio/permission-manager#36]
thanks for the new release! how do we upgrade from 1.5.0 to 1.6.0?

**Comment by iknite** [comment]
Hi @viorel-anghel,

The main difference between v1.5.0 and  v1.6.0 is that the users have been replaced with service-accounts to be usable in EKS and other user-managed authentication middlewares. 

That said, there is no need to migrate, users created in v1.5.X will continue to be usable in v1.6.0 (usable in terms of that the users access the cluster). Even it can coexist users created with v1.5.X with the new ones. 

If you want to change the users (v1.5.X) to the service accounts (v1.6.0) The best way is to delete the seeds, the clusterroles and clusterrolebindings, then the roles and rolebindings please remember to use `-A` to check all namespaces. 

There is no way to change automatically to user-based to service-account manager without create everything again (nor kubeconfigs nor RBACs are reusable switching from one method to another)

hope it solves all your doubts.

**Comment by viorel-anghel** [comment]
so with this new version i will be able to _manage_ users created with version 1.5 (for example to add a new namespace to an exisiting user)?

**Comment by iknite** [comment]
No, v1.5.0 should be maintained with the  same container's version.

**Comment by viorel-anghel** [comment]
so basically permission manager 1.6 has nothing to do with permission manager 1.5?

have you considered a way to manage both "old" users and the "new" service accounts within a unified permission manager version?

**Comment by iknite** [comment]
It's on the roadmap, without a given deadline nor a milestone. There are other refactors on the table right now.

Thanks for the feedback! Feel free to reopen if the Original Post is unclear.
