### ISSUE TITLE
Helm chart for permission-manager does not work

### ISSUE THREAD

**Issue by sramek5** [sighupio/permission-manager#37]
When I make helm chart, I always get error:
```
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.3.10-dev
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
{"time":"2020-06-09T12:11:22.343530878Z","level":"FATAL","prefix":"echo","file":"run-server.go","line":"17","message":"listen tcp: address tcp/4000\n: unknown port"}
```

I solved this manually:
1) Made a namespace,
2) Applied filled secret,
3) Applied my Helm Chart.

Unfortunately, this worked only one time. I am not able to install it again.

This is anusual behavior for helm, can you fix it please? Secret should be part of the Helm Chart.

**Comment by phisco** [comment]
Sorry @sramek5, the project does not provide an helm chart installation, so I guess you mean that the chart you wrote is not working properly, right?

**Comment by sramek5** [comment]
Hi @phisco, yes it is my own helm chart.
Later I was able to find a problem. In our infrastructure we are using coded and sealed passwords. Permission manager cannot be used with base64 coding.

Echo would read base64 coded port/password/whatever (seen in logs), but it has "unknown" problem with it.

So now it works with stringData password (not coded).

Still, thank you for your app, it looks it is one of its kind :-)
I was just wondering, are you planning some version, where would be possible to make even templates in the GUI?
Admin could choose resources, permissions etc. ? 
Not just adding template manually.

That would be great feature :-)

**Comment by phisco** [comment]
Perfect, good to know! Feel free to close the issue if that’s the case!

CC @iknite for the roadmap questions

**Comment by iknite** [comment]
We will add the feature requested in the backlog, we're in the middle on another huge refactor, so maybe after that could make it. 

Thanks for your interest and feedback for this tool, we're proud of this little piece. 

(I'm closing the issue since but feel free to reopen it if you feel it to)

**Comment by sramek5** [comment]
Thank you @iknite for answer.

That would be grate.
