### ISSUE TITLE
Restricted when trying to log in

### ISSUE THREAD

**Issue by Endriuz1805** [sighupio/permission-manager#40]
Hi,

After performing the steps described on the installation page, i get Restricted access when trying to log in.
Tried to change the password several times, but without luck.

Any thoughts would be greatly appreciated.

Thanks

**Comment by angelbarrera92** [comment]
Hi @Endriuz1805. 

1st of all, sorry for the late reply.
Did you solve the issue? Otherwise try to login usin the `admin` user and the password output from:

```
kubectl get secret -n permission-manager permission-manager -o jsonpath='{.data.BASIC_AUTH_PASSWORD}' | base64 -d && echo
```

Thanks!
