### ISSUE TITLE
Lens not showing metrics to user who can only access some namespaces

### ISSUE THREAD

**Issue by fahadh4ilyas** [sighupio/permission-manager#43]
Is there a way that even though the user is only granted full access to some namespaces, the user still can see the metrics from Lens app? Because the user can't see the namespaces resources this way.

**Comment by angelbarrera92** [comment]
Hi @fahadh4ilyas.

With permission manager, you can assign full access to certain namespaces without giving them permissions to interact at cluster level. 

What is Lens? Thanks!

**Comment by Slach** [comment]
@angelbarrera92 https://k8slens.dev/

**Comment by angelbarrera92** [comment]
Ok, but what is the issue?

To test it I've installed lens in my pc (latest version running on macOS)

Then, I've created a user with permissions to access only to `local-path-provisioner` namespace
![Captura de pantalla 2020-10-26 a las 13 17 04](https://user-images.githubusercontent.com/14357604/97171314-8c80a200-178d-11eb-9422-576a42b7e356.png)

With the generated kubeconfig, I've configured lens to use it:

![Captura de pantalla 2020-10-26 a las 13 15 59](https://user-images.githubusercontent.com/14357604/97171242-65c26b80-178d-11eb-97f0-31665439b709.png)

I can see only the resources of the `local-path-provisioner` namespace. 

What is the issue?

**Comment by fahadh4ilyas** [comment]
@angelbarrera92 The issue is, Lens usually showing metrics like `CPU` and `Memory` from nodes dan pods. But, using permission manager, it's not showing up. Here is example of metrics

![image](https://user-images.githubusercontent.com/37577369/100313619-97765e80-2fe7-11eb-84c5-c128f9397aaa.png)

**Comment by angelbarrera92** [comment]
> @angelbarrera92 The issue is, Lens usually showing metrics like `CPU` and `Memory` from nodes dan pods. But, using permission manager, it's not showing up. Here is example of metrics
> 
> ![image](https://user-images.githubusercontent.com/37577369/100313619-97765e80-2fe7-11eb-84c5-c128f9397aaa.png)

Then what is missing is the right role. I discovered that lens is using Prometheus under the hood to gather the metrics. **I'll take a deeper look.** 

Meanwhile, if you know already know the specific Role/ClusterRole needed to make it working, ping me :)

**Comment by angelbarrera92** [comment]
I was able to make it work by applying a "wide" ClusterRole I found here: https://github.com/lensapp/lens/pull/644/files

I'll open a PR to modify the ReadOnly access to cluster resources (non-namespaced).
As far as I could test, you can not see only namespaced metrics... That sucks!
