### ISSUE TITLE
Namespaces starting with kube are excluded in namespace overview

### ISSUE THREAD

**Issue by tplueer** [sighupio/permission-manager#55]
First of all thanks for creating this tool it really helps a lot!

I'm wondering why will "kube" Namespaces be excluded from the overview, i guess for security reasons ? 

https://github.com/sighupio/permission-manager/blob/3a9cf1847816d4c4d9dab7598b8d4d7e1c0f177e/web-client/src/components/NamespaceMultiSelect.tsx#L23-L27

Can we provide an option to show namespaces starting with "kube" so rolebindings can be set also for this namespace? 
Maybe a configuration variable during setup or a checkbox in the UI ?

Thanks!

**Comment by Rampage1xx** [comment]
Hello @tplueer,
Thanks for the feedback, we are looking into this!
