### ISSUE TITLE
Bug when deleting users with same prefix

### ISSUE THREAD

**Issue by Hayyk** [sighupio/permission-manager#59]
I have created 2 users: test and test2
if I delete test2 user everything is ok and test user is still available
if I delete test user, test2 user is gone from cluster but still it's showing in permission manager and if I click on username in permission manager application hangs. I've created rolebinding manually in order to bring back user and make application work again.

Same behavior was for 2+ users with the following names:
user
user-dev
user-test
user-staging
user-prod
I deleted user and all other users(rb,sa) were deleted from cluster but they still exist in permission-manager and when I click on one of them the app hangs.

**Comment by Rampage1xx** [comment]
Hello, 
Thanks for the report!
We found the issue and are proceeding to fix it
