### ISSUE TITLE
How to get user token for the k8s dashboard?

### ISSUE THREAD

**Issue by ArjonBu** [sighupio/permission-manager#6]
It looks like you can't authenticate on k8s dashboard using the k8s kubeconfig generated by permission manager. How do you get the token to also use the kubernetes dashboard?

**Comment by angelbarrera92** [comment]
Hi @ArjonBu.

This project creates `kubeconfig` for users using certificates. Unfortunately `kubernetes dashboard` does not support this kind of `kubeconfig`:

 >   Kubeconfig Authentication method does not support external identity providers or certificate based authentication.

*source: https://github.com/kubernetes/dashboard#create-an-authentication-token-rbac*
