### ISSUE TITLE
bug when creating users with same prefix

### ISSUE THREAD

**Issue by Hayyk** [sighupio/permission-manager#61]
Using v1.16.0
There is a bug when creating users with same prefix. Steps to reproduce:
1. create user with name test in namespace1 with operator role
2. create user with name test2 in namespace2 or namespace1 with operator/developer role
3. edit user test and you will see namespace2 with appropriate role has been added to test user. if you try to delete that role, and then open test2 user application hangs and no test2 user/rolebinding exists in cluster

**Comment by phisco** [comment]
Should have been fixed by #60, @angelbarrera92 is working on releasing a release-candidate you will be able to test.

**Comment by Hayyk** [comment]
@phisco thx, will wait to test and give feedback

**Comment by angelbarrera92** [comment]
Ciao @Hayyk i've released a release candidate of permission manager that should fix the issue:
Test it out by following: https://github.com/sighupio/permission-manager/blob/master/docs/installation.md

Thanks!

**Comment by Hayyk** [comment]
Hi @angelbarrera92 
Just run 1.7.0-rc1 in my cluster and I can confirm that issue during creation and deletion of users with same prefix solved. but there is another bug. Whatever role I'm setting for my users it shows developer role, but I'm checking the rolebinding inside the cluster and it bind the right clusterrole (e.g. template-namespaced-resources___operation). 

P.S. should I create new issue?

**Comment by angelbarrera92** [comment]
> Hi @angelbarrera92
> Just run 1.7.0-rc1 in my cluster and I can confirm that issue during creation and deletion of users with same prefix solved. but there is another bug. Whatever role I'm setting for my users it shows developer role, but I'm checking the rolebinding inside the cluster and it bind the right clusterrole (e.g. template-namespaced-resources___operation).
> 
> P.S. should I create new issue?

Ciao @Hayyk, sorry for reading that, yes please, in order to keep the issue board as clean as possible, create a new one. Thanks!

**Comment by Hayyk** [comment]
Hi @angelbarrera92
done
