### ISSUE TITLE
Showing developer role in UI even if other role is set for user

### ISSUE THREAD

**Issue by Hayyk** [sighupio/permission-manager#62]
Using 1.7.0-rc1:
Whatever role I'm setting for my users it shows developer role in UI, but I'm checking the rolebinding inside the cluster and it binds the right clusterrole (e.g. template-namespaced-resources___operation). this behavior exists for custom templates as well as for templates added from seeds.yaml

**Comment by angelbarrera92** [comment]
A new release candidate has been released solving this issue. Please give it a try: https://github.com/sighupio/permission-manager/releases/tag/v1.7.0-rc2

**Comment by Hayyk** [comment]
Hi @angelbarrera92 ,
Fixed, thank you

**Comment by angelbarrera92** [comment]
> Hi @angelbarrera92 ,
> Fixed, thank you

kudos to @Rampage1xx !!! He actually fixes the problem.
