### ISSUE TITLE
UX: The username suggestion is invalid

### ISSUE THREAD

**Issue by ralgozino** [sighupio/permission-manager#73]
When creating a new user in Permission Manager, the username field suggests as an example `Jane Doe`, but if you write that you get an error message saying that the username is not valid:
![Screenshot 2021-08-13 at 10 11 26](https://user-images.githubusercontent.com/6362698/129326266-6e48cabd-59d8-4a9c-92ba-50855023a925.png)
![Screenshot 2021-08-13 at 10 15 28](https://user-images.githubusercontent.com/6362698/129326364-d020bab2-3b34-4ed9-9949-e4155efb08db.png)

**Comment by ralgozino** [comment]
also, "[...] dots and dashes and numbers" shuold be "[...] dots, dashes and numbers"

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by ralgozino** [comment]
The PR didn't fix the issue. The placeholder problem is still present.

**Comment by angelbarrera92** [comment]
I think the problem is not only about the tooltip or the placeholder:

1st issue: The place holder "Jane Doe" is an invalid username. Consider using a valid one like: `jane.doe`.
2nd issue: The validation is incorrect. Backend and frontend are not checking the same regex pattern. In addition, the tooltip is incorrect right now.

Frontend:
```typescript
    if (
      !username.match(/^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)$/)) {
      setUsernameError(`user can only contain lowercase letters, dots, dashes and numbers`)
      return false
    }
```

Backend:

```go
const validUsernameRegex = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"

var invalidUsernameError = `username must be DNS-1123 compliant, it must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'gino.mycompany', regex used for validation is ` + validUsernameRegex

func isValidUsername(username string) (valid bool) {
	re := regexp.MustCompile(validUsernameRegex)
	return re.MatchString(username)
}
```

We must align these patterns

**Comment by divanikus** [comment]
For some reason it doesn't accept names with dot in the middle, despite of tooltip saying `jane.doe` is allowed.

![image](https://user-images.githubusercontent.com/3438036/136113913-f604f87b-9b34-43b2-bf46-3b4994ae3545.png)

Running latest v1.7.1-rc1

**Comment by DesSolo** [comment]
https://github.com/sighupio/permission-manager/pull/182
