### ISSUE TITLE
Created user cannot authenticate

### ISSUE THREAD

**Issue by i5okie** [sighupio/permission-manager#8]
I've created users with operation/all-namespaces/read-write permissions.
When I merge into my existing /config:
k get pods
`error: You must be logged in to the server (Unauthorized)`

k version
`error: You must be logged in to the server (the server has asked for the client to provide credentials)`

When I point to generated kube config saved to a file, and  k version:
`Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")`

**Comment by angelbarrera92** [comment]
Hi @i5okie, What kind of cluster are you using? How did you created the certificates?
Thanks!

**Comment by i5okie** [comment]
a mix of kops and eks clusters

**Comment by angelbarrera92** [comment]
Hi @i5okie, 

Can you try running:

`k version --insecure-skip-tls-verify=true` with the generated kube-config saved in a separate file?

Thanks

**Comment by i5okie** [comment]
```shell
$ k version --insecure-skip-tls-verify=true --kubeconfig my-config.config
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

**Comment by i5okie** [comment]
I've re-tried on the kops cluster. and now im seeing 
`Unable to connect to the server: x509: certificate signed by unknown authority` instead.

**Comment by i5okie** [comment]
@angelbarrera92 could it be because of me using an ELB with a https cert from aws certificate management?

**Comment by angelbarrera92** [comment]
> @angelbarrera92 could it be because of me using an ELB with a https cert from aws certificate management?

Is the TLS certificate signed by an authoritative CA? (Trusted)

If the enpoint is public, can you send us the link? We can validate the TLS certificate

**Comment by i5okie** [comment]
it is public but i don't want to share it :)

One more thing I've tried. I looked at kops created config and it adds username/password along with cert. Also kops does not include CA data in the cluster section.
```yaml
- name: jonas-dev.ac-dev.io
  user:
    client-certificate-data: LS0tLS...==
    client-key-data: EgUFJJVkFURSB....==
    password: vkmnwH6uVhdPS8H9LYIE
    username: admin
```

And if I remove username and password. I get the same thing:
```error: You must be logged in to the server (Unauthorized)```

**Comment by angelbarrera92** [comment]
Lets take a deeper look @iknite

**Comment by iknite** [comment]
On my way

**Comment by i5okie** [comment]
Just tried on to run kubectl commands on windows. just for sanity's sake.
same result. So to sum it up:

kubernetes api is exposed on a public domain via ELB with a signed/valid tls cert.
https://api.mycluster.domain.com

With `certificate-authority-data` being set in kube config I get:
```Unable to connect to the server: x509: certificate signed by unknown authority```

Without `certificate-authority-data`, or with `--insecure-skip-tls-verify=true` i get:
```error: You must be logged in to the server (the server has asked for the client to provide credentials)```

**Comment by colegatron** [comment]
Same issue here:
`k version --insecure-skip-tls-verify=true --kubeconfig config-k8s-new
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
`

**Comment by iknite** [comment]
Hi folks, 

I've been digging around this and I can confirm is related to the way EKS does the authorization through IAM roles. We're further investigating the issue and the possible solutions. 

If you want to know more about the authorization model, please check https://kreuzwerker.de/post/managed-kubernetes-eks-cluster-authentication-and-autoscaling

**Comment by i5okie** [comment]
What about the kops cluster?

**Comment by iknite** [comment]
@i5okie we make some quick test and it worked with this bare minimum kops setup. 
```
aws s3 mb s3://permission-manager-8
export KOPS_STATE_STORE=s3://permission-manager-8
kops create cluster --zones eu-central-1a --name permission-manager-8.k8s.local
kops update cluster permission-manager-8.k8s.local --yes
```

**Comment by i5okie** [comment]
@iknite  does this make a difference:
```yaml
kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```

**Comment by iknite** [comment]
Permission manager relies on X509  in this version (1.5.0) so disabling it will not work AFAIK. 

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/#kubelet-authentication

**Comment by angelbarrera92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change permission-manager from X509 to serviceAccount (to be used in EKS clusters)](https://trello.com/c/xkbQNEKJ/174-change-permission-manager-from-x509-to-serviceaccount-to-be-used-in-eks-clusters)

**Comment by i5okie** [comment]
I'm still confused. So I'm still having this issue with a KOPS cluster.
As far as I can tell, I have not disabled X509
this is from cluster.yaml for kops:
```yaml
# ...
authorization:
    rbac: {}
# ...
kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
# ...
```

Regardless, if this change comes along to using serviceAccounts. It will be really helpful!
