### ISSUE TITLE
Kubeconfig in UI missing certificate-authority-data value

### ISSUE THREAD

**Issue by andrey-gava** [sighupio/permission-manager#89]
After update from v1.6.0 to 1.7.1-rc1 the value fro the key certificate-authority-data in kubeconfig are missing for new created user and old users too.

![изображение](https://user-images.githubusercontent.com/59727632/136175972-61bd205d-7066-4039-a436-ec8189a373de.png)

**Comment by RestfulLeo23** [comment]
Any update on this?

**Comment by paulrostorp** [comment]
I managed to get it to work using the docker image tagged `9f717d02c3509607daf23481f3868888c163d0e4` (see https://quay.io/repository/sighup/permission-manager?tab=tags&tag=latest)

**Comment by YFrendo** [comment]
Same issue here. On a microk8s cluster (if it can help)

**Comment by thegalah** [comment]
@paulrostorp s solution worked for me
